alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: longhorn
grafana:
  admin:
    existingSecret: "grafana-admin-credentials"
    userKey: GRAFANA_ADMIN_USER
    passwordKey: GRAFANA_ADMIN_PASSWORD
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    size: 5Gi
    storageClassName: longhorn
    type: pvc
  service:
    nodePort: 30090
    type: NodePort
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn
prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
