apiVersion: apps/v1
kind: Deployment
metadata:
  name: moadong
  labels:
    app: moadong
spec:
  selector:
    matchLabels:
      app: moadong
  template:
    metadata:
      labels:
        app: moadong
    spec:
      containers:
        - name: moadong
          image: moadong/moadong-dev
          ports:
            - containerPort: 8080
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
