apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moadong-tailscale-ingress
  namespace: moadong
  annotations:
    tailscale.com/hostname: backend
spec:
  ingressClassName: tailscale
  rules:
    - host: backend.alpines-bebop.ts.net
      http:
        paths:
          - backend:
              service:
                name: moadong-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
