apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moadong-backend-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Moadong/gitops-moadong.git
    targetRevision: HEAD
    path: backend/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: moadong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
