apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moadong-backend-prod
  namespace: argocd
  labels:
    app: moadong
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord-prod: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord-prod: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord-prod: ""
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Moadong/gitops-moadong.git
    targetRevision: HEAD
    path: backend/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: moadong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
