apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretNamespace: moadong-dev
      secretsScope:
        envSlug: dev
  managedSecretReference:
    secretNamespace: moadong-dev
