apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moadong-dev

resources:
- ../base
- issuer-staging.yaml

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: moadong
- path: ingress.yaml
  target:
    kind: Ingress
    name: moadong-ingress

images:
- name: moadong/moadong-dev
  newName: moadong/moadong-dev
  newTag: ed0e103
