apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: argocd-infisical-secret
  namespace: argocd
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: monitoring
      secretsScope:
        envSlug: prod
        secretsPath: /
  managedSecretReference:
    secretName: argocd-notifications-secret
    secretNamespace: argocd
